export const datas: any[]  = [
    {
      id: 1,
      name: "Znika Rhiel Madsen",
      email: "example@email.com",
      status: "Active",
      lastLogin: "14/APR/2020",
      paymentStatus: "Overdue",
      dueDate: "15/APR/2020",
      amount: 300,
      currency: "USD",
      activities: [
        {
          date: "12/APR/2020",
          activity: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ultricies.",
          detail: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Rhoncus, sed purus eu semper morbi id nunc, adipiscing vitae. Ultricies suspendisse vestibulum."
        },
      ],
      showDescription: false
    },
    {
      id: 2,
      name: "John Doe",
      email: "john.doe@email.com",
      status: "Inactive",
      lastLogin: "10/APR/2020",
      paymentStatus: "Pending",
      dueDate: "20/APR/2020",
      amount: 150,
      currency: "USD",
      activities: [],
      showDescription: false
    },
    {
      id: 3,
      name: "Jane Smith",
      email: "jane.smith@email.com",
      status: "Active",
      lastLogin: "08/APR/2020",
      paymentStatus: "Paid",
      dueDate: "12/APR/2020",
      amount: 0,
      currency: "USD",
      activities: [],
      showDescription: false
    },
    {
      id: 4,
      name: "Robert Brown",
      email: "robert.brown@email.com",
      status: "Active",
      lastLogin: "05/APR/2020",
      paymentStatus: "Overdue",
      dueDate: "11/APR/2020",
      amount: 200,
      currency: "USD",
      activities: [],
      showDescription: false
    },
    {
      id: 5,
      name: "Emily Davis",
      email: "emily.davis@email.com",
      status: "Inactive",
      lastLogin: "02/APR/2020",
      paymentStatus: "Pending",
      dueDate: "09/APR/2020",
      amount: 100,
      currency: "USD",
      activities: [],
      showDescription: false
    },
    {
      id: 6,
      name: "Alice Johnson",
      email: "alice.johnson@email.com",
      status: "Inactive",
      lastLogin: "15/APR/2020",
      paymentStatus: "Paid",
      dueDate: "18/APR/2020",
      amount: 250,
      currency: "USD",
      activities: [],
      showDescription: false
    },
    {
      id: 7,
      name: "Chris Lee",
      email: "chris.lee@email.com",
      status: "Inactive",
      lastLogin: "12/APR/2020",
      paymentStatus: "Overdue",
      dueDate: "22/APR/2020",
      amount: 300,
      currency: "USD",
      activities: [],
      showDescription: false
    },
    {
      id: 8,
      name: "David Wilson",
      email: "david.wilson@email.com",
      status: "Inactive",
      lastLogin: "17/APR/2020",
      paymentStatus: "Pending",
      dueDate: "25/APR/2020",
      amount: 175,
      currency: "USD",
      activities: [],
      showDescription: false
    },
    {
      id: 9,
      name: "Eva Green",
      email: "eva.green@email.com",
      status: "Inactive",
      lastLogin: "11/APR/2020",
      paymentStatus: "Paid",
      dueDate: "15/APR/2020",
      amount: 50,
      currency: "USD",
      activities: [],
      showDescription: false
    },
    {
      id: 10,
      name: "Frank Wright",
      email: "frank.wright@email.com",
      status: "Inactive",
      lastLogin: "16/APR/2020",
      paymentStatus: "Overdue",
      dueDate: "18/APR/2020",
      amount: 200,
      currency: "USD",
      activities: [],
      showDescription: false
    },
    {
      id: 11,
      name: "Grace Hall",
      email: "grace.hall@email.com",
      status: "Inactive",
      lastLogin: "13/APR/2020",
      paymentStatus: "Pending",
      dueDate: "20/APR/2020",
      amount: 100,
      currency: "USD",
      activities: [],
      showDescription: false
    },
    {
      id: 12,
      name: "Hannah Baker",
      email: "hannah.baker@email.com",
      status: "Active",
      lastLogin: "19/APR/2020",
      paymentStatus: "Paid",
      dueDate: "21/APR/2020",
      amount: 300,
      currency: "USD",
      activities: [],
      showDescription: false
    },
    {
      id: 13,
      name: "Ian Harris",
      email: "ian.harris@email.com",
      status: "Inactive",
      lastLogin: "20/APR/2020",
      paymentStatus: "Overdue",
      dueDate: "25/APR/2020",
      amount: 200,
      currency: "USD",
      activities: [],
      showDescription: false
    },
    {
      id: 14,
      name: "Jack White",
      email: "jack.white@email.com",
      status: "Active",
      lastLogin: "21/APR/2020",
      paymentStatus: "Pending",
      dueDate: "28/APR/2020",
      amount: 150,
      currency: "USD",
      activities: [],
      showDescription: false
    },
    {
      id: 15,
      name: "Karen Black",
      email: "karen.black@email.com",
      status: "Inactive",
      lastLogin: "22/APR/2020",
      paymentStatus: "Paid",
      dueDate: "29/APR/2020",
      amount: 50,
      currency: "USD",
      activities: [],
      showDescription: false
    },
    {
      id: 16,
      name: "Liam Moore",
      email: "liam.moore@email.com",
      status: "Active",
      lastLogin: "23/APR/2020",
      paymentStatus: "Overdue",
      dueDate: "30/APR/2020",
      amount: 300,
      currency: "USD",
      activities: [],
      showDescription: false
    },
    {
      id: 17,
      name: "Mia Clark",
      email: "mia.clark@email.com",
      status: "Inactive",
      lastLogin: "24/APR/2020",
      paymentStatus: "Pending",
      dueDate: "01/MAY/2020",
      amount: 100,
      currency: "USD",
      activities: [],
      showDescription: false
    },
    {
      id: 18,
      name: "Noah Martin",
      email: "noah.martin@email.com",
      status: "Active",
      lastLogin: "25/APR/2020",
      paymentStatus: "Paid",
      dueDate: "03/MAY/2020",
      amount: 250,
      currency: "USD",
      activities: [],
      showDescription: false
    },
    {
      id: 19,
      name: "Olivia Davis",
      email: "olivia.davis@email.com",
      status: "Inactive",
      lastLogin: "26/APR/2020",
      paymentStatus: "Overdue",
      dueDate: "05/MAY/2020",
      amount: 300,
      currency: "USD",
      activities: [],
      showDescription: false
    },
    {
      id: 20,
      name: "Paul King",
      email: "paul.king@email.com",
      status: "Active",
      lastLogin: "27/APR/2020",
      paymentStatus: "Pending",
      dueDate: "07/MAY/2020",
      amount: 150,
      currency: "USD",
      activities: [],
      showDescription: false
    }
  ];
